### ISSUE TITLE
[connector.Discord] HTTPs in Requests.py fails in Python <2.7

### ISSUE THREAD

**Issue by ZetaHunter** [ph7vc/Arcbot#25]
The current version of Arcbot uses HTTP for XHR and V2 on websockets, which means we are behind the rest of the people and http causes issues on native (electron) clients for link embeds.
Ex of link embed bug: http://vgy.me/KrYCRx.png

I personally patched this issue on my local clone, and have yet to encounter any issues.
However I am running Python 3.5 exclusively, as such I can not guarantee stability of bot under Python 2.7.

**Comment by ph7vc** [comment]
Returns this stacktrace when attempting to use SSL with requests:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    main()
  File "bot.py", line 26, in main
    bot.login()
  File "/home/raynor/Gameon/arcbot/core/Core.py", line 57, in login
    self.connection.connect()
  File "connectors/Discord.py", line 75, in connect
    self.socket = websocket.create_connection(self.socketURL)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 104, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 266, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options))
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 69, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 160, in _ssl_socket
    match_hostname(sock.getpeercert(), hostname)
  File "/usr/lib/python2.7/ssl.py", line 187, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname u'gateway-zerg.discord.gg' doesn't match either of

**Comment by ph7vc** [comment]
This is isolated to any version before Python 2.7.9

https://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent
https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

Both solutions failed; and the doc's have little about why this exception is being thrown.

**Comment by ZetaHunter** [comment]
Tried out using Python 2.7 on my Tartarus server, seems to work fine for me.

**Comment by ph7vc** [comment]
Tested it with 2.7.4; no dice.

**Comment by ph7vc** [comment]
Going to just stick to Python 3.4 from now on
