### ISSUE TITLE
[core.Core] Multiplexing bot connections

### ISSUE THREAD

**Issue by ph7vc** [ph7vc/Arcbot#35]
Had a thought today:

Since loading the core instance from bot.py, seems like it wouldn't be difficult to run multiple bot instances from a single bot.py file, just need to create more core objects.

So this could allow the bot to connect to multiple chat sources at once, or connect to the same one multiple times. 

Only issue I see is that this could be resource costly. So could I set it up to allow this, while sharing resources like worker threads, databases, etc?

**Comment by ZetaHunter** [comment]
This does sound nice in my opinion.

**Comment by ZetaHunter** [comment]
I do however have to note that current User structure in database as you have it is not going to handle multiple connectors simultaneously well.

**Comment by ph7vc** [comment]
Yeah I know, I'm not sure how I could change it to fit into this easily without making it super weird and hacky.

**Comment by ZetaHunter** [comment]
Well as I did suggest before, having a Master Account / Slave User relationship.
A Master Account would link all Connector specific users together (aka Slave Users).
Master Account would store Access, Bans, Grants and etc.
Slave User would store connector specific data like UID for that service and other things.

**Comment by ZetaHunter** [comment]
Okay I've added Connection model now which is a model consisting of User reference, Connector name (maybe append name of user/bot in case the bot actually runs several Discord bots in multiplexing) and a TextField `metadata` which could contain a blob (JSON maybe?) of data specific to connector .

Also I am trying to make the Data classes functional, right now I am trying out Dependency Injection.
Which usually assumes a singleton Core...

So with Functional Data Classes (things like member.mention(), channel.send_file(), channel.say(), channel.mention(), etc) I will need to add multiprocessing ( Spawn new process for every Core )
